version: "3.7"
services:
  seleniumTest:
    image: golang:1.13.1
    container_name: seleniumTest
    volumes:
      - ./main.go:/go/src/app/main.go
      - ./vendor:/go/src/app/vendor
    working_dir: /go/src/app
    tty: true