version: "3.7"
services: 
  proxyserver:
    build: ./proxyserver
    image: proxyserver
    container_name: proxyserver
    ports:
      - 8080:8080
    tty: true
    volumes: 
      - ./proxyserver:/go/src/proxyserver
    working_dir: /go/src/proxyserver
    networks:
      - selenium

networks:
  selenium:
    name: selenium-net